using System;

namespace Project.NET
{
    public partial class admission_data : System.Web.UI.Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {
            if (IsPostBack) return; // Prevents re-execution on postbacks

            // Check session for user authentication and role
            if (Session["UserId"] != null && Session["Role"] != null)
            {
                string userRole = Session["Role"].ToString();

                // Set GridView buttons based on user role
                if (userRole.Equals("Administration", StringComparison.OrdinalIgnoreCase) ||
                    userRole.Equals("Admin", StringComparison.OrdinalIgnoreCase))
                {
                    GridView1.AutoGenerateDeleteButton = true;
                    GridView1.AutoGenerateEditButton = true;
                }
            }

            // Check for redirect session variable
            if (Session["RedirectToDashboard"] is bool redirect && redirect)
            {
                Session["RedirectToDashboard"] = false; // Clear the session variable
                Response.Redirect("dashboard.aspx"); // Redirect to the dashboard
            }
        }
    }
}
