<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="dashboard.aspx.cs" Inherits="Project.NET.dashboard" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>DASHBOARD</title>
    <style type="text/css">
        body {
            margin: 0;
            font-family: Arial, sans-serif;
            color: #333;
        }

        .dashboard {
            display: flex;
            height: 100vh;
        }

        .sidebar {
            width: 250px;
            background-color: #2c3e50;
            color: white;
            padding-top: 20px;
            box-shadow: 2px 0 5px rgba(0, 0, 0, 0.1);
            height: fit-content;
        }

        .sidebar h2 {
            margin-top: 0;
        }

        .sidebar nav ul {
            list-style: none;
            padding: 0;
        }

        .sidebar nav ul li {
            padding: 15px 0;
            margin: 15px 0;
        }

        .sidebar nav ul li a {
            padding-left: 10px;
            color: #ecf0f1;
            text-decoration: none;
            font-size: 18px;
        }

        .sidebar nav ul li a:hover {
            text-decoration: underline;
            color: chocolate;
        }

        li:hover {
            background-color: rgb(177, 205, 233);
            box-shadow: 0px 6px blue;
            transition: ease 0.3s;
            font-weight: bold;
        }

        .main-content {
            flex: 1;
            display: flex;
            flex-direction: column;
        }

        .header {
            background-color: #3498db;
            color: white;
            padding: 15px;
            text-align: center;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
        }

        .content {
            padding: 20px;
        }

        .content h2 {
            margin-top: 0;
        }

        .grid-container {
            border: 1px solid gray;
            border-radius: 2%;
            box-shadow: 6px 6px 12px 12px silver;
            background-color: floralwhite;
            width: fit-content;
            padding: 2%;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
        <div class="dashboard">
            <aside class="sidebar">
                <h2>College Dashboard</h2>
                <nav>
                    <ul>
                        <li><asp:LinkButton ID="Home" runat="server" PostBackUrl="~/index.aspx">HOME</asp:LinkButton></li>
                        <li><asp:LinkButton ID="Profiles" runat="server" PostBackUrl="~/profile_selection.aspx">PROFILE</asp:LinkButton></li>
                        <li><asp:LinkButton ID="Details" runat="server" PostBackUrl="~/details.aspx">DETAILS</asp:LinkButton></li>
                        <li><asp:LinkButton ID="Log_Out" runat="server" OnClick="Log_Out_Click">LOG_OUT</asp:LinkButton></li>
                        <li ><asp:LinkButton ID="Result" runat="server" PostBackUrl="~/Result.aspx">RESULT</asp:LinkButton></li>
                        <li><asp:LinkButton ID="Fee_Payment" runat="server" PostBackUrl="~/FeePayment.aspx">FEE_PAYMENT</asp:LinkButton></li>
                        <li><asp:LinkButton ID="Students" runat="server" PostBackUrl="~/students.aspx">STUDENTS</asp:LinkButton></li>
                        <li><asp:LinkButton ID="Admission" runat="server" PostBackUrl="~/admission_data.aspx">ADMISSION</asp:LinkButton></li>
                        <li><asp:LinkButton ID="Faculties" runat="server" PostBackUrl="~/faculties.aspx">FACULTIES</asp:LinkButton></li>
                        <li><asp:LinkButton ID="Administration" runat="server" PostBackUrl="~/Administration.aspx">ADMINISTRATION</asp:LinkButton></li>
                    </ul>
                </nav>
            </aside>
            <div class="main-content">
                <header class="header">
                    <h1 id="Welcome">Welcome</h1>
                </header>
                <section class="content">
                    <h2>Dashboard Content</h2>
                    <div class="grid-container">
                        <asp:GridView ID="GridView1" runat="server" DataKeyNames="Id" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BackColor="White" BorderColor="#3366CC" BorderStyle="None" BorderWidth="1px" CellPadding="4" DataSourceID="SqlDataSource1" OnRowUpdating="GridView1_RowUpdating">
                            <FooterStyle BackColor="#99CCCC" ForeColor="#003399" />
                            <HeaderStyle BackColor="#003399" Font-Bold="True" ForeColor="#CCCCFF" />
                            <PagerStyle BackColor="#99CCCC" ForeColor="#003399" HorizontalAlign="Left" />
                            <RowStyle BackColor="White" ForeColor="#003399" />
                            <SelectedRowStyle BackColor="#009999" Font-Bold="True" ForeColor="#CCFF99" />
                            <SortedAscendingCellStyle BackColor="#EDF6F6" />
                            <SortedAscendingHeaderStyle BackColor="#0D4AC4" />
                            <SortedDescendingCellStyle BackColor="#D6DFDF" />
                            <SortedDescendingHeaderStyle BackColor="#002876" />
                        </asp:GridView>
                        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:dbcol %>" 
                            DeleteCommand="DELETE FROM [Data] WHERE [Id] = @Id" 
                            InsertCommand="INSERT INTO [Data] ([Name], [Age], [Email], [Role], [UserId], [Password], [Phone], [Gender]) VALUES (@Name, @Age, @Email, @Role, @UserId, @Password, @Phone, @Gender)" 
                            SelectCommand="SELECT * FROM [Data]" 
                            UpdateCommand="UPDATE [Data] SET [Name] = @Name, [Age] = @Age, [Email] = @Email, [Role] = @Role, [UserId] = @UserId, [Password] = @Password, [Phone] = @Phone, [Gender] = @Gender WHERE [Id] = @Id">
                            <DeleteParameters>
                                <asp:Parameter Name="Id" Type="Int32" />
                            </DeleteParameters>
                            <InsertParameters>
                                <asp:Parameter Name="Name" Type="String" />
                                <asp:Parameter Name="Age" Type="Int32" />
                                <asp:Parameter Name="Email" Type="String" />
                                <asp:Parameter Name="Role" Type="String" />
                                <asp:Parameter Name="UserId" Type="String" />
                                <asp:Parameter Name="Password" Type="String" />
                                <asp:Parameter Name="Phone" Type="String" />
                                <asp:Parameter Name="Gender" Type="String" />
                            </InsertParameters>
                            <UpdateParameters>
                                <asp:Parameter Name="Name" Type="String" />
                                <asp:Parameter Name="Age" Type="Int32" />
                                <asp:Parameter Name="Email" Type="String" />
                                <asp:Parameter Name="Role" Type="String" />
                                <asp:Parameter Name="UserId" Type="String" />
                                <asp:Parameter Name="Password" Type="String" />
                                <asp:Parameter Name="Phone" Type="String" />
                                <asp:Parameter Name="Gender" Type="String" />
                                <asp:Parameter Name="Id" Type="Int32" />
                            </UpdateParameters>
                        </asp:SqlDataSource>
                    </div>
                </section>
            </div>
        </div>
    </form>
</body>
</html>
